import Head from 'next/head';
import { Container } from 'react-bootstrap';
import Hero from '../components/hero';
import Section from '../components/section';
import Header from '../components/header';
import Opportunity from '../components/opportunity';
import Footer from '../components/footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <Header />
      <Hero />
      <Section />
      <Opportunity />
      <Footer />
    </>
  );
}
